name: Ping Backend Every 15 Minutes

on:
  schedule:
    - cron: '*/14 * * * *'  # This runs the action every 15 minutes
  workflow_dispatch:  # This allows you to manually trigger the workflow from GitHub if needed

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request to backend
        run: |
          curl -X GET https://blog-backend-yashkhalkar.onrender.com  # Replace with your actual endpoint
